name: Local-Action-Test

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Test ssm-to-env local
      uses: ./
      id: ssm-to-env-local
      with:
        ssm-path: /actions-testing/test-parameter
        decryption: true

    - name: Test for Env Variables
      run: |
        echo "Testing if parameter values get set properly:"
        printenv
