name: Local-Action-Test

on:
  push:
    branches: [ develop, main ]
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Test ssm-to-env local json
      uses: ./
      id: ssm-to-env-local-json
      with:
        ssm-path: /actions-testing/test-parameter
        decryption: false

    - name: Test ssm-to-env local encrypted
      uses: ./
      id: ssm-to-env-local-encrypted
      with:
        ssm-path: /actions-testing/test-parameter-encrypted
        decryption: true

    - name: Test ssm-to-env local non-json
      uses: ./
      id: ssm-to-env-local-non-json
      with:
        ssm-path: /actions-testing/test-parameter-basic
        decryption: false

    - name: Test for Env Variables
      run: |
        echo "Testing if parameter values get set properly:"
        printenv
